# Generated by Django 6.0.6 on 2026-07-04 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('ntn_cnic', models.CharField(blank=True, max_length=15)),
                ('registration_type', models.CharField(choices=[('Registered', 'Registered'), ('Unregistered', 'Unregistered')], default='Unregistered', max_length=20)),
                ('province', models.CharField(choices=[('Sindh', 'Sindh'), ('Punjab', 'Punjab'), ('KPK', 'KPK'), ('Balochistan', 'Balochistan'), ('Islamabad', 'Islamabad'), ('AJK', 'AJK'), ('Gilgit-Baltistan', 'Gilgit-Baltistan')], default='Sindh', max_length=30)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('Sale Invoice', 'Sale Invoice'), ('Debit Note', 'Debit Note')], default='Sale Invoice', max_length=30)),
                ('invoice_date', models.DateField()),
                ('scenario_id', models.CharField(blank=True, max_length=10)),
                ('seller_ntn_cnic', models.CharField(max_length=15)),
                ('seller_business_name', models.CharField(max_length=255)),
                ('seller_province', models.CharField(max_length=30)),
                ('seller_address', models.CharField(max_length=500)),
                ('buyer_ntn_cnic', models.CharField(blank=True, max_length=15)),
                ('buyer_business_name', models.CharField(max_length=255)),
                ('buyer_province', models.CharField(max_length=30)),
                ('buyer_address', models.CharField(blank=True, max_length=500)),
                ('buyer_registration_type', models.CharField(default='Unregistered', max_length=20)),
                ('invoice_ref_no', models.CharField(blank=True, max_length=100)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_sales_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_further_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('valid', 'Valid'), ('failed', 'Failed')], default='draft', max_length=10)),
                ('fbr_invoice_number', models.CharField(blank=True, max_length=60)),
                ('fbr_dated', models.CharField(blank=True, max_length=30)),
                ('fbr_payload', models.JSONField(blank=True, null=True)),
                ('fbr_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='digital_invoicing.buyer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=500)),
                ('sale_type', models.CharField(max_length=60)),
                ('uom', models.CharField(default='Numbers, pieces, units', max_length=60)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('value_excl_st', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('rate', models.CharField(blank=True, max_length=10)),
                ('sales_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('further_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sro_schedule', models.CharField(blank=True, max_length=60)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='digital_invoicing.invoice')),
            ],
        ),
    ]
