# Generated by Django 5.0.7 on 2026-07-06 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('profile_saved', 'Profile saved'), ('invoice_valid', 'Invoice validated'), ('invoice_failed', 'Invoice rejected'), ('invoice_printed', 'Invoice printed')], max_length=30)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='digital_inv_user_id_d17294_idx'), models.Index(fields=['action'], name='digital_inv_action_b0d8ab_idx')],
            },
        ),
    ]
