# Generated by Django 5.2.15 on 2026-07-05 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntn_cnic', models.CharField(max_length=15, verbose_name='NTN / CNIC')),
                ('business_name', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('Sindh', 'Sindh'), ('Punjab', 'Punjab'), ('KPK', 'KPK'), ('Balochistan', 'Balochistan'), ('Islamabad', 'Islamabad'), ('AJK', 'AJK'), ('Gilgit-Baltistan', 'Gilgit-Baltistan')], default='Sindh', max_length=30)),
                ('address', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
