# Generated by Django 5.0.7 on 2026-07-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0003_invoice_seller_profile_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=12, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('uoms', models.CharField(blank=True, help_text='Pipe-separated, pehla default (e.g. KG|Bag)', max_length=255)),
                ('default_sale_type', models.CharField(choices=[('Goods at standard rate', 'Goods at standard rate'), ('Goods at reduced rate', 'Goods at reduced rate'), ('3rd Schedule Goods', '3rd Schedule Goods'), ('Exempt Goods', 'Exempt Goods'), ('Zero-rated Goods', 'Zero-rated Goods'), ('Services', 'Services')], default='Goods at standard rate', max_length=40)),
                ('schedule_hint', models.CharField(blank=True, help_text="e.g. '3rd Schedule — retail price pe ST'", max_length=120)),
                ('note', models.CharField(blank=True, help_text='Practitioner note / VERIFY flag', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hs_code'],
            },
        ),
    ]
