# Generated by Django 5.0.7 on 2026-07-09 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0004_hscode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['-last_used']},
        ),
        migrations.AddField(
            model_name='buyer',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyer',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=255)),
                ('sale_type', models.CharField(default='Goods at standard rate', max_length=40)),
                ('uom', models.CharField(default='Numbers, pieces, units', max_length=50)),
                ('last_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-times_used', '-last_used'],
                'unique_together': {('owner', 'hs_code', 'description')},
            },
        ),
    ]
