# Generated by Django 5.0.7 on 2026-07-10 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0005_alter_buyer_options_buyer_last_used_buyer_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='strn',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sales Tax Reg No (STRN)'),
        ),
        migrations.CreateModel(
            name='ATLStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(db_index=True, max_length=20)),
                ('period', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atl_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['owner', 'reg_no', 'period'], name='digital_inv_owner_i_6cbbab_idx')],
                'unique_together': {('owner', 'reg_no', 'period')},
            },
        ),
    ]
