# Generated by Django 5.0.7 on 2026-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0006_buyer_strn_atlstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='fbr_token',
            field=models.CharField(blank=True, help_text='PRAL se mila Bearer token (5-saal)', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='use_sandbox',
            field=models.BooleanField(default=True, help_text='ON = sandbox/testing; OFF = production'),
        ),
    ]
