# Generated by Django 6.0.7 on 2026-07-10 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0007_sellerprofile_fbr_token_sellerprofile_use_sandbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='public_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='extra_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fed_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sales_tax_withheld',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='sro_item_serial_no',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_values',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fbr_invoice_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('valid', 'Valid'), ('failed', 'Failed'), ('pending_retry', 'Pending Retry'), ('edited', 'Edited'), ('cancelled', 'Cancelled'), ('partially_edited', 'Partially Edited'), ('partially_cancelled', 'Partially Cancelled'), ('partially_edited_cancelled', 'Partially Edited & Cancelled')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
        ),
        migrations.AddIndex(
            model_name='buyer',
            index=models.Index(fields=['owner', 'ntn_cnic'], name='digital_inv_owner_i_b7eb1e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner', 'status'], name='digital_inv_owner_i_7bedd7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner', '-invoice_date'], name='digital_inv_owner_i_570471_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='digital_inv_invoice_2c08b8_idx'),
        ),
    ]
