# Generated by Django 6.0.7 on 2026-07-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0009_data_prep_unique_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='fbr_invoice_number',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='public_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
