# Generated by Django 6.0.7 on 2026-07-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0010_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurtherTaxConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legal_reference', models.CharField(blank=True, default='Section 3(1A), Sales Tax Act 1990', max_length=200)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TaxScenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('sale_type', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FurtherTaxExemptHS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_prefix', models.CharField(max_length=12)),
                ('sro_reference', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Further-tax exempt HS prefix',
                'verbose_name_plural': 'Further-tax exempt HS prefixes',
                'ordering': ['hs_prefix'],
                'indexes': [models.Index(fields=['hs_prefix'], name='digital_inv_hs_pref_d55e1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaxSaleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('charges_st', models.BooleanField(default=True)),
                ('further_tax_applies', models.BooleanField(default=False)),
                ('sro_schedule', models.CharField(blank=True, default='', max_length=80)),
                ('retail_price_based', models.BooleanField(default=False)),
                ('fbr_trans_type_id', models.IntegerField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('legal_reference', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name', '-effective_from'],
                'indexes': [models.Index(fields=['name', 'effective_from'], name='digital_inv_name_aa9f99_idx')],
            },
        ),
    ]
