# Generated by Django 5.2.15 on 2026-07-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0012_seed_tax_rules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FurtherTaxConfig',
        ),
        migrations.DeleteModel(
            name='FurtherTaxExemptHS',
        ),
        migrations.DeleteModel(
            name='TaxSaleType',
        ),
        migrations.DeleteModel(
            name='TaxScenario',
        ),
    ]
