# Generated by Django 6.0.7 on 2026-07-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0013_erp_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='fbr_token',
            field=models.CharField(blank=True, help_text='PRAL se mila Bearer token (5-saal)', max_length=512),
        ),
    ]
