# Generated by Django 5.2.15 on 2026-07-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0013_delete_furthertaxconfig_delete_furthertaxexempths_and_more'),
        ('digital_invoicing', '0015_encrypt_tokens'),
    ]

    operations = [
    ]
