# Generated by Django 6.0.7 on 2026-07-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0015_encrypt_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlstatus',
            name='evidence_pdf',
            field=models.FileField(blank=True, null=True, upload_to='atl_evidence/%Y/%m/'),
        ),
    ]
