# Generated by Django 6.0.7 on 2026-07-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0016_atl_evidence_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlstatus',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
