# Generated by Django 5.0.7 on 2026-07-13 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0016_atl_evidence_pdf'),
        ('digital_invoicing', '0017_furthertaxconfig_taxscenario_furthertaxexempths_and_more'),
    ]

    operations = [
    ]
