# Generated by Django 6.0.7 on 2026-07-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0017_atl_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsaletype',
            name='rate_label',
            field=models.CharField(blank=True, default='', help_text='Exact PRAL rate string, e.g. "Rs.3" ya "18% along with rupees 60 per kilogram". Khali = "<rate>%"', max_length=60),
        ),
        migrations.AddField(
            model_name='taxsaletype',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxsaletype',
            name='rate_type',
            field=models.CharField(choices=[('percent', 'Percent of value'), ('fixed_per_unit', 'Fixed Rs. per unit (qty x Rs.X)'), ('compound', 'Percent + Rs. per unit'), ('exempt', 'Exempt (no ST)')], default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='taxsaletype',
            name='sro_item_serial',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='default_sale_type',
            field=models.CharField(choices=[('Goods at standard rate (default)', 'Goods at standard rate (default)'), ('Goods at Reduced Rate', 'Goods at Reduced Rate'), ('3rd Schedule Goods', '3rd Schedule Goods'), ('Exempt goods', 'Exempt goods'), ('Goods at zero-rate', 'Goods at zero-rate'), ('Steel melting and re-rolling', 'Steel melting and re-rolling'), ('Ship breaking', 'Ship breaking'), ('Cotton ginners', 'Cotton ginners'), ('Telecommunication services', 'Telecommunication services'), ('Toll Manufacturing', 'Toll Manufacturing'), ('Petroleum Products', 'Petroleum Products'), ('Electricity Supply to Retailers', 'Electricity Supply to Retailers'), ('Gas to CNG stations', 'Gas to CNG stations'), ('Mobile Phones', 'Mobile Phones'), ('Processing/Conversion of Goods', 'Processing/Conversion of Goods'), ('Goods (FED in ST Mode)', 'Goods (FED in ST Mode)'), ('Services (FED in ST Mode)', 'Services (FED in ST Mode)'), ('Services', 'Services'), ('Electric Vehicle', 'Electric Vehicle'), ('Cement /Concrete Block', 'Cement /Concrete Block'), ('Potassium Chlorate', 'Potassium Chlorate'), ('CNG Sales', 'CNG Sales'), ('Goods as per SRO.297(|)/2023', 'Goods as per SRO.297(|)/2023'), ('Non-Adjustable Supplies', 'Non-Adjustable Supplies'), ('Goods at standard rate', 'Goods at standard rate'), ('Goods at reduced rate', 'Goods at reduced rate'), ('Exempt Goods', 'Exempt Goods'), ('Zero-rated Goods', 'Zero-rated Goods')], default='Goods at standard rate', max_length=40),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='rate',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
