# Generated by Django 6.0.7 on 2026-07-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0017_atl_verified'),
        ('digital_invoicing', '0018_merge_20260713_1124'),
    ]

    operations = [
    ]
