# Generated by Django 6.0.7 on 2026-07-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0019_merge_0017_atl_verified_0018_merge_20260713_1124'),
        ('digital_invoicing', '0019_seed_pral_sale_types_scenarios'),
    ]

    operations = [
    ]
