# Generated by Django 6.0.7 on 2026-07-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0019_seed_pral_sale_types_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('edited', 'Edited')], default='active', max_length=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='original_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('profile_saved', 'Profile saved'), ('invoice_valid', 'Invoice validated'), ('invoice_failed', 'Invoice rejected'), ('invoice_printed', 'Invoice printed'), ('invoice_cancelled', 'Invoice cancelled'), ('item_cancelled', 'Invoice item cancelled'), ('item_edited', 'Invoice item edited')], max_length=30),
        ),
    ]
