# Generated by Django 6.0.7 on 2026-07-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0020_invoiceitem_cancelled_at_invoiceitem_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='invoice',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
