# Generated by Django 6.0.7 on 2026-07-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0020_merge_20260714_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsaletype',
            name='rate_label',
            field=models.CharField(blank=True, default='', help_text='Exact PRAL rate string, e.g. "Rs.3" ya "18% along with rupees 60 per kilogram". Khali = "<rate>%"', max_length=60),
        ),
        migrations.AddField(
            model_name='taxsaletype',
            name='rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxsaletype',
            name='rate_type',
            field=models.CharField(choices=[('percent', 'Percent of value'), ('fixed_per_unit', 'Fixed Rs. per unit (qty x Rs.X)'), ('compound', 'Percent + Rs. per unit'), ('exempt', 'Exempt (no ST)')], default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='taxsaletype',
            name='sro_item_serial',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
