# Generated by Django 6.0.7 on 2026-07-14 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0020_invoiceitem_cancelled_at_invoiceitem_edited_at_and_more'),
        ('digital_invoicing', '0021_taxsaletype_rate_label_taxsaletype_rate_per_unit_and_more'),
    ]

    operations = [
    ]
