# Generated by Django 6.0.7 on 2026-07-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0021_invoice_last_error_invoice_next_retry_at_and_more'),
        ('digital_invoicing', '0022_merge_20260714_1229'),
    ]

    operations = [
    ]
