# Generated by Django 6.0.7 on 2026-07-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0022_fix_third_schedule_sro'),
        ('digital_invoicing', '0023_merge_20260714_1642'),
    ]

    operations = [
    ]
