# Generated by Django 6.0.7 on 2026-07-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0023_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('profile_saved', 'Profile saved'), ('invoice_valid', 'Invoice validated'), ('invoice_failed', 'Invoice rejected'), ('invoice_printed', 'Invoice printed'), ('invoice_cancelled', 'Invoice cancelled'), ('item_cancelled', 'Invoice item cancelled'), ('item_edited', 'Invoice item edited'), ('invoices_exported', 'Invoice list exported'), ('token_updated', 'FBR token updated'), ('token_removed', 'FBR token removed')], max_length=30),
        ),
    ]
