# Generated by Django 5.2.15 on 2026-07-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0024_alter_auditlog_action'),
        ('digital_invoicing', '0024_merge_20260715_1132'),
    ]

    operations = [
    ]
