# Generated by Django 6.0.7 on 2026-07-16 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0025_alter_auditlog_action'),
        ('digital_invoicing', '0025_merge_20260716_0146'),
    ]

    operations = [
    ]
