# Generated by Django 6.0.7 on 2026-07-17 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0025_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('valid_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('cancelled_count', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_sales_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_further_tax', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('first_fbr_number', models.CharField(blank=True, default='', max_length=60)),
                ('last_fbr_number', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closings', to='digital_invoicing.sellerprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('seller_profile', 'date')},
            },
        ),
    ]
