# Generated by Django 6.0.7 on 2026-07-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0026_dailyclosing'),
        ('digital_invoicing', '0026_merge_20260716_1135'),
    ]

    operations = [
    ]
