# Generated by Django 6.0.7 on 2026-07-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0026_dailyclosing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='business_activity',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_sector',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
