# Generated by Django 6.0.7 on 2026-07-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0027_merge_0026_dailyclosing_0026_merge_20260716_1135'),
        ('digital_invoicing', '0027_sellerprofile_business_activity_and_more'),
    ]

    operations = [
    ]
