# Generated by Django 6.0.7 on 2026-07-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0027_sellerprofile_business_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscode',
            name='auto_synced',
            field=models.BooleanField(default=False),
        ),
    ]
