# Generated by Django 6.0.7 on 2026-07-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0028_hscode_auto_synced'),
        ('digital_invoicing', '0028_merge_20260721_1538'),
    ]

    operations = [
    ]
