# Generated by Django 6.0.7 on 2026-07-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0028_hscode_auto_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='withholding_category',
            field=models.CharField(blank=True, choices=[('', 'None — not a withholding agent'), ('1/5', '1/5th of Sales Tax'), ('1/10', '1/10th of Sales Tax'), ('1/1', 'Whole of Sales Tax')], default='', max_length=6),
        ),
    ]
