# Generated by Django 6.0.7 on 2026-07-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0029_buyer_withholding_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='withholding_category',
            field=models.CharField(blank=True, choices=[('', 'None — not withheld'), ('S1', 'S.1 — Govt/company buyer, ATL supplier: 1/5 of ST'), ('S2', 'S.2 — Govt/company buyer, ATL wholesaler/dealer/distributor: 1/10 of ST'), ('S3', 'S.3 — Govt buyer, non-ATL supplier: whole of ST (gross-value basis)'), ('S4', 'S.4 — Company buyer, non-ATL supplier: 5% of gross value'), ('S5', 'S.5 — Advertisement services: whole of ST'), ('S6', 'S.6 — Cane molasses, non-ATL supplier: whole of ST'), ('S7', 'S.7 — Lead/batteries supplier: 80% of ST'), ('S8', 'S.8 — Payment intermediary/courier, digital goods: 2% of gross value'), ('S9', 'S.9 — Gypsum/limestone to cement mfr: 80% of ST'), ('S10', 'S.10 — Coal supplier: 80% of ST'), ('S11', 'S.11 — Waste paper/board supplier: 80% of ST'), ('S12', 'S.12 — Plastic waste supplier: 80% of ST'), ('S13', 'S.13 — Crush stone & silica supplier: 80% of ST'), ('S14', 'S.14 — Toll manufacturing, unregistered buyer: 4x tax on conversion charges')], default='', max_length=4),
        ),
    ]
