# Generated by Django 6.0.7 on 2026-07-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_invoicing', '0029_merge_20260721_1639'),
        ('digital_invoicing', '0030_alter_buyer_withholding_category'),
    ]

    operations = [
    ]
